// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProcessPaymentApi.Entities;

namespace ProcessPaymentApi.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20210325174953_ProcessPaymentmigration")]
    partial class ProcessPaymentmigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ProcessPaymentApi.Entities.ProcessPayment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Amount")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CardHolder")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreditCardNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SecurityCode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ProcessPayment_tbl");
                });

            modelBuilder.Entity("ProcessPaymentApi.Entities.ProcessStatus", b =>
                {
                    b.Property<long>("ProcessStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("CardId")
                        .HasColumnType("bigint");

                    b.Property<string>("ProcessStatusName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProcessStatusId");

                    b.HasIndex("CardId")
                        .IsUnique();

                    b.ToTable("processStatuses");
                });

            modelBuilder.Entity("ProcessPaymentApi.Entities.ProcessStatus", b =>
                {
                    b.HasOne("ProcessPaymentApi.Entities.ProcessPayment", "ProcessPayment")
                        .WithOne("ProcessStatus")
                        .HasForeignKey("ProcessPaymentApi.Entities.ProcessStatus", "CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProcessPayment");
                });

            modelBuilder.Entity("ProcessPaymentApi.Entities.ProcessPayment", b =>
                {
                    b.Navigation("ProcessStatus");
                });
#pragma warning restore 612, 618
        }
    }
}
